variables:
  IMAGE: "deployment-build-image:20210614.01"
  BUNDLE_PATH: "${CI_PROJECT_DIR}/vendor/bundle"
  BUNDLE_JOBS: 4
  BUNDLE_RETRY: 10
  YARN_CACHE_FOLDER: .yarn

cache:
  key:
    files:
      - Gemfile
      - wipe_out.gemspec
    prefix: v1-${CI_PROJECT_ID}
  paths:
     - vendor/bundle

before_script:
  - bundle install -j4

lint:
  image: ${AWS_ECR_URL}/${IMAGE}
  tags:
    - size-s
  script:
    - bundle exec standardrb --format progress --no-fix
    - yarn global add markdownlint-cli@0.27.1
    - export PATH="${PATH}:$(yarn global bin)"
    - markdownlint --config .markdownlint.json -i .yarn -i vendor .

tests:
  image: ${AWS_ECR_URL}/${IMAGE}
  tags:
    - size-s
  script:
    - bundle exec rspec

doc:
  image: ${AWS_ECR_URL}/${IMAGE}
  except:
    - master
  script:
    - bin/yard
  artifacts:
    paths:
      - doc
    expire_in: 2d

pages:
  image: ${AWS_ECR_URL}/${IMAGE}
  only:
    - master
  script:
    - bin/yard
    - mv doc public
  artifacts:
    paths:
      - public
