variables:
  IMAGE: "deployment-build-image:20210614.01"
  BUNDLE_PATH: "${CI_PROJECT_DIR}/vendor/bundle"
  BUNDLE_JOBS: 4
  BUNDLE_RETRY: 10

cache:
  key:
    files:
      - Gemfile
      - wipe_out.gemspec
    prefix: v1-${CI_PROJECT_ID}
  paths:
     - vendor/bundle

before_script:
  - bundle install -j4

lint:
  image: ${AWS_ECR_URL}/${IMAGE}
  tags:
    - size-s
  allow_failure: true
  script:
    - bundle exec standardrb --format progress

tests:
  image: ${AWS_ECR_URL}/${IMAGE}
  tags:
    - size-s
  script:
    - bundle exec rspec
